# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='treetype',
            name='fruit_name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Fruit name'),
        ),
        migrations.AddField(
            model_name='treetype',
            name='fruit_name_fr',
            field=models.CharField(max_length=20, null=True, verbose_name='Fruit name'),
        ),
        migrations.AddField(
            model_name='treetype',
            name='name_en',
            field=models.CharField(default=b'', max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='treetype',
            name='name_fr',
            field=models.CharField(default=b'', max_length=20, null=True, verbose_name='Name'),
        ),
    ]
