# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforparticipation',
            name='picker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Picker'),
        ),
    ]
