# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20160618_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='harvest.Property', verbose_name='Property'),
        ),
    ]
