# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20160621_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforparticipation',
            name='is_accepted',
            field=models.NullBooleanField(default=None, verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='showed_up',
            field=models.NullBooleanField(default=None, verbose_name='Showed up'),
        ),
    ]
