# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20180507_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='about',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='property',
            name='about',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='validated',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Additional information'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='authorized',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property has been authorized for the current season by its owner', verbose_name='Authorized for this season'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='pending',
            field=models.BooleanField(default=b'True', help_text='This property was created through a public form and needs to be validated', verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='pending_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='pending_contact_name',
            field=models.CharField(default='Anon', max_length=50, verbose_name='Contact name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='pending_contact_phone',
            field=models.CharField(default='no phone', max_length=50, verbose_name='Phone number for contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Additional information'),
        ),
        migrations.AddField(
            model_name='property',
            name='authorized',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property has been authorized for the current season by its owner', verbose_name='Authorized for this season'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=b'True', help_text='This property was created through a public form and needs to be validated', verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending_contact_name',
            field=models.CharField(default='Adnon', max_length=50, verbose_name='Contact name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='pending_contact_phone',
            field=models.CharField(default='no phone', max_length=50, verbose_name='Phone number for contact'),
            preserve_default=False,
        ),
    ]
