# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20160620_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='nb_required_pickers',
            field=models.PositiveIntegerField(default=3, verbose_name='Number of required pickers'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='owner_help',
            field=models.BooleanField(default=False, verbose_name='Owner wants to participate'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='owner_no_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner does not want his share of fruits'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='owner_present',
            field=models.BooleanField(default=False, verbose_name='Owner wants to be present'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='nb_required_pickers',
            field=models.PositiveIntegerField(default=3, verbose_name='Number of required pickers'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='owner_help',
            field=models.BooleanField(default=False, verbose_name='Owner wants to participate'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='owner_no_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner does not want his share of fruits'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='owner_present',
            field=models.BooleanField(default=False, verbose_name='Owner wants to be present'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='avg_nb_required_pickers',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Required pickers on average'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='compost_bin',
            field=models.BooleanField(default=False, verbose_name='Compost bin closeby'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='neighbor_access',
            field=models.BooleanField(default=False, verbose_name='Access to neighboring terrain if needed'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='public_access',
            field=models.BooleanField(default=False, verbose_name='Publicly accessible'),
        ),
        migrations.AlterField(
            model_name='property',
            name='avg_nb_required_pickers',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Required pickers on average'),
        ),
        migrations.AlterField(
            model_name='property',
            name='compost_bin',
            field=models.BooleanField(default=False, verbose_name='Compost bin closeby'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighbor_access',
            field=models.BooleanField(default=False, verbose_name='Access to neighboring terrain if needed'),
        ),
        migrations.AlterField(
            model_name='property',
            name='public_access',
            field=models.BooleanField(default=False, verbose_name='Publicly accessible'),
        ),
    ]
