# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20180514_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalharvest',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='pick_leader',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='state',
        ),
        migrations.DeleteModel(
            name='HistoricalHarvest',
        ),
        migrations.DeleteModel(
            name='HistoricalProperty',
        ),
    ]
