# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20160620_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='harvest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='leader_need_help',
            field=models.BooleanField(default=False, help_text='Check the About field for details', verbose_name='Pick leader needs extra help'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='leader_need_help',
            field=models.BooleanField(default=False, help_text='Check the About field for details', verbose_name='Pick leader needs extra help'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='cross_street',
            field=models.CharField(blank=True, help_text='Closest corner, used as a hint for location', max_length=50, null=True, verbose_name='Cross street'),
        ),
        migrations.AddField(
            model_name='property',
            name='cross_street',
            field=models.CharField(blank=True, help_text='Closest corner, used as a hint for location', max_length=50, null=True, verbose_name='Cross street'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest is authorized for the current season', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest is authorized for the current season', verbose_name='Is active'),
        ),
    ]
