# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_treetype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforparticipation',
            name='number_of_people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='How many people are you?'),
        ),
    ]
