# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20160620_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='pickers',
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='picker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Person', verbose_name='Requester'),
        ),
    ]
