# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20160621_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproperty',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property is authorized for the current season', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property is authorized for the current season', verbose_name='Is active'),
        ),
    ]
