# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20160624_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforparticipation',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_participation', to='harvest.Harvest', verbose_name='Harvest'),
        ),
    ]
