# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20180514_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Actor', verbose_name='Owner'),
        ),
    ]
