# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0005_requestforparticipation_comment_about_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='owner_fruit',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalharvest',
            name='owner_fruit',
        ),
        migrations.RemoveField(
            model_name='requestforparticipation',
            name='comment_about_participation',
        ),
        migrations.AddField(
            model_name='harvest',
            name='leader_need_help',
            field=models.BooleanField(default=False, help_text='Check the About field for details', verbose_name='Pick leader needs extra help'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='owner_no_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner does not want his share of fruits'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='leader_need_help',
            field=models.BooleanField(default=False, help_text='Check the About field for details', verbose_name='Pick leader needs extra help'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='owner_no_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner does not want his share of fruits'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='cross_street',
            field=models.CharField(blank=True, help_text='Closest corner, used as a hint for location', max_length=50, null=True, verbose_name='Cross street'),
        ),
        migrations.AddField(
            model_name='property',
            name='cross_street',
            field=models.CharField(blank=True, help_text='Closest corner, used as a hint for location', max_length=50, null=True, verbose_name='Cross street'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='about',
            field=models.TextField(blank=True, help_text='If any help is needed from volunteer pickers, please describe them in this box.', max_length=1000, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='nb_required_pickers',
            field=models.PositiveIntegerField(default=3, verbose_name='Number of required pickers'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='owner_help',
            field=models.BooleanField(default=False, verbose_name='Owner wants to participate'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='owner_present',
            field=models.BooleanField(default=False, verbose_name='Owner wants to be present'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='about',
            field=models.TextField(blank=True, help_text='If any help is needed from volunteer pickers, please describe them in this box.', max_length=1000, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='nb_required_pickers',
            field=models.PositiveIntegerField(default=3, verbose_name='Number of required pickers'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='owner_help',
            field=models.BooleanField(default=False, verbose_name='Owner wants to participate'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='owner_present',
            field=models.BooleanField(default=False, verbose_name='Owner wants to be present'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='avg_nb_required_pickers',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Required pickers on average'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='compost_bin',
            field=models.BooleanField(default=False, verbose_name='Compost bin closeby'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property is authorized for the current season', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='neighbor_access',
            field=models.BooleanField(default=False, verbose_name='Access to neighboring terrain if needed'),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='public_access',
            field=models.BooleanField(default=False, verbose_name='Publicly accessible'),
        ),
        migrations.AlterField(
            model_name='property',
            name='avg_nb_required_pickers',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Required pickers on average'),
        ),
        migrations.AlterField(
            model_name='property',
            name='compost_bin',
            field=models.BooleanField(default=False, verbose_name='Compost bin closeby'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=b'True', help_text='Harvest in this property is authorized for the current season', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighbor_access',
            field=models.BooleanField(default=False, verbose_name='Access to neighboring terrain if needed'),
        ),
        migrations.AlterField(
            model_name='property',
            name='public_access',
            field=models.BooleanField(default=False, verbose_name='Publicly accessible'),
        ),
    ]
