# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_auto_20180515_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='authorized',
            field=models.BooleanField(default=False, help_text='Harvest in this property has been authorized for the current season by its owner', verbose_name='Authorized for this season'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=True, help_text='This property was created through a public form and needs to be validated', verbose_name='Pending'),
        ),
    ]
