# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_auto_20160621_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='cross_street',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cross_street',
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='publishable_location',
            field=models.CharField(blank=True, help_text='Aproximative location, do not make public the real address.', max_length=50, null=True, verbose_name='Publishable location'),
        ),
        migrations.AddField(
            model_name='property',
            name='publishable_location',
            field=models.CharField(blank=True, help_text='Aproximative location, do not make public the real address.', max_length=50, null=True, verbose_name='Publishable location'),
        ),
    ]
