# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0007_auto_20160621_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='historicalharvest',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
    ]
