# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0007_auto_20180515_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Any additional information that we should be aware of', max_length=1000, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='property',
            name='approximative_maturity_date',
            field=models.DateField(blank=True, help_text='When is the tree commonly ready to be harvested?', null=True, verbose_name='Approximative maturity date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending_contact_email',
            field=models.EmailField(blank=True, help_text='Email address to be used for confirmation', max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending_contact_name',
            field=models.CharField(help_text='Name of the person to be contacted for confirmation', max_length=50, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending_contact_phone',
            field=models.CharField(help_text='Phone number to be used for confirmation', max_length=50, verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='publishable_location',
            field=models.CharField(blank=True, help_text='Aproximative location to be used in public communications (not the actual address)', max_length=50, null=True, verbose_name='Publishable location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='trees_accessibility',
            field=models.CharField(blank=True, help_text='Any info on how to access the tree (eg. key, gate etc)', max_length=200, null=True, verbose_name='Trees accessibility'),
        ),
        migrations.AlterField(
            model_name='property',
            name='trees_location',
            field=models.CharField(blank=True, help_text='Front yard or backyard?', max_length=200, null=True, verbose_name='Trees location'),
        ),
    ]
