# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20160702_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestyield',
            name='total_in_lb',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Weight (lb)'),
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='How many people are you?'),
        ),
    ]
