# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20160621_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'harvests_images')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='harvest.Harvest')),
            ],
        ),
        migrations.AddField(
            model_name='requestforparticipation',
            name='notes_from_pickleader',
            field=models.TextField(blank=True, null=True, verbose_name='Notes from the pick leader.'),
        ),
    ]
