# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20180516_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This property exists and may be able to host a pick', verbose_name='Is active'),
        ),
    ]
