# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0009_auto_20180517_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='about',
        ),
        migrations.AddField(
            model_name='property',
            name='pending_newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter subscription'),
        ),
        migrations.AddField(
            model_name='property',
            name='pending_recurring',
            field=models.BooleanField(default=False, verbose_name='Recurring property signup'),
        ),
    ]
