# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0009_auto_20160702_1540'),
        ('harvest', '0009_auto_20160702_1558'),
    ]

    operations = [
    ]
