# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_auto_20180530_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='authorized',
            field=models.NullBooleanField(default=None, help_text='Harvest in this property has been authorized for the current season by its owner', verbose_name='Authorized for this season'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_trees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of trees/vines on this property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=True, help_text='This property was created through a public form and needs to be validated by an administrator', verbose_name='Pending'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='trees',
            field=models.ManyToManyField(help_text='Select multiple fruit types if applicable. Unknown fruit type or colour can be mentioned in the additional comments at the bottom.', to='harvest.TreeType', verbose_name='Fruit tree/vine type(s)'),
        ),
    ]
