# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0009_auto_20160702_1729'),
        ('harvest', '0010_merge'),
    ]

    operations = [
    ]
