# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_merge'),
        ('harvest', '0011_auto_20160702_2129'),
    ]

    operations = [
    ]
