# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_auto_20180620_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='owner_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner wants his share of fruits'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=True, help_text='This property was created through a public form and needs to be validated by an administrator', verbose_name='Pending validation'),
        ),
    ]
