# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_auto_20180612_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='authorized',
            field=models.NullBooleanField(default=None, help_text='Harvest in this property has been authorized for the current season by its owner', verbose_name='Authorized for this season'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=True, help_text='This property was created through a public form and needs to be validated by an administrator', verbose_name='Pending'),
        ),
    ]
