# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_auto_20160720_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='about',
            field=models.TextField(blank=True, help_text='If any help is needed from volunteer pickers, please describe them here.', max_length=1000, null=True, verbose_name='Public announcement'),
        ),
        migrations.AlterField(
            model_name='historicalharvest',
            name='about',
            field=models.TextField(blank=True, help_text='If any help is needed from volunteer pickers, please describe them here.', max_length=1000, null=True, verbose_name='Public announcement'),
        ),
    ]
