# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 13:36
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_auto_20160720_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
