# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-07 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_auto_20170507_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='approximative_maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approximative maturity date'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='fruits_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height of lowest fruits'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='harvest_every_year',
            field=models.BooleanField(default=False, verbose_name='Produces fruits every year'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='ladder_available',
            field=models.BooleanField(default=False, verbose_name='There is a ladder available in the property'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='ladder_available_for_outside_picks',
            field=models.BooleanField(default=False, verbose_name='A ladder is available in the property and can be used for nearby picks'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='number_of_trees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of trees in this property'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='trees_accessibility',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Trees accessibility'),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='validated',
            field=models.BooleanField(default=b'True', help_text='This property data has been reviewed and validatedby a collective member', verbose_name='Validated'),
        ),
        migrations.AddField(
            model_name='property',
            name='approximative_maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approximative maturity date'),
        ),
        migrations.AddField(
            model_name='property',
            name='fruits_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height of lowest fruits'),
        ),
        migrations.AddField(
            model_name='property',
            name='harvest_every_year',
            field=models.BooleanField(default=False, verbose_name='Produces fruits every year'),
        ),
        migrations.AddField(
            model_name='property',
            name='ladder_available',
            field=models.BooleanField(default=False, verbose_name='There is a ladder available in the property'),
        ),
        migrations.AddField(
            model_name='property',
            name='ladder_available_for_outside_picks',
            field=models.BooleanField(default=False, verbose_name='A ladder is available in the property and can be used for nearby picks'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_trees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of trees in this property'),
        ),
        migrations.AddField(
            model_name='property',
            name='trees_accessibility',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Trees accessibility'),
        ),
        migrations.AddField(
            model_name='property',
            name='validated',
            field=models.BooleanField(default=b'True', help_text='This property data has been reviewed and validatedby a collective member', verbose_name='Validated'),
        ),
    ]
