# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_auto_20170507_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalharvest',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproperty',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
