# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-07 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0016_auto_20180220_1152'),
        ('harvest', '0016_auto_20180507_1544'),
    ]

    operations = [
    ]
